# Generated by Django 6.0.3 on 2026-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigoblog',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='autor_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='citacao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='citacao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='legenda',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='legenda2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='primeiro_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='quarto_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sub_imagem/'),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='segundo_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='terceiro_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
