# Generated by Django 6.0.3 on 2026-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_remove_reserva_email_remove_reserva_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoblog',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='autor_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores'),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='citacao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='citacao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sub_imagem'),
        ),
    ]
