# Generated by Django 6.0.3 on 2026-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_artigoblog_autor_artigoblog_autor_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoblog',
            name='legenda',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
