# Generated by Django 6.0.3 on 2026-04-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_artigoblog_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigoblog',
            name='legenda2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
