# Generated by Django 6.0.3 on 2026-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_artigoblog_legenda2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigoblog',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='primeiro_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='quarto_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='segundo_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='artigoblog',
            name='terceiro_paragrafo',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
