# Generated by Django 6.0.3 on 2026-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_remove_artigoblog_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigoblog',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='autor_imagem',
            field=models.ImageField(null=True, upload_to='autores'),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='citacao1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='citacao2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='legenda2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='primeiro_paragrafo',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='quarto_paragrafo',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='segunda_imagem',
            field=models.ImageField(null=True, upload_to='sub_imagem'),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='segundo_paragrafo',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='artigoblog',
            name='terceiro_paragrafo',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
